2025-05-30 10:41:12,837 INFO    MainThread:60884 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/marco/projects/flawfinder/comments-categorizer-model/wandb/run-20250530_104112-g1jjd4pv/logs/debug.log
2025-05-30 10:41:12,837 INFO    MainThread:60884 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/marco/projects/flawfinder/comments-categorizer-model/wandb/run-20250530_104112-g1jjd4pv/logs/debug-internal.log
2025-05-30 10:41:12,837 INFO    MainThread:60884 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd1aa7313a0>
2025-05-30 10:41:12,837 INFO    MainThread:60884 [wandb_init.py:init():852] calling init triggers
2025-05-30 10:41:12,837 INFO    MainThread:60884 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.1, 'max_depth': 8, 'n_estimators': 200, 'eval_metric': 'logloss', 'use_label_encoder': False, '_wandb': {}}
2025-05-30 10:41:12,837 INFO    MainThread:60884 [wandb_init.py:init():893] starting backend
2025-05-30 10:41:12,837 INFO    MainThread:60884 [wandb_init.py:init():897] sending inform_init request
2025-05-30 10:41:12,838 INFO    MainThread:60884 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-30 10:41:12,839 INFO    MainThread:60884 [wandb_init.py:init():907] backend started and connected
2025-05-30 10:41:12,843 INFO    MainThread:60884 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-05-30 10:41:12,844 INFO    MainThread:60884 [wandb_init.py:init():1005] updated telemetry
2025-05-30 10:41:12,847 INFO    MainThread:60884 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-30 10:41:13,398 INFO    MainThread:60884 [wandb_init.py:init():1104] starting run threads in backend
2025-05-30 10:41:13,505 INFO    MainThread:60884 [wandb_run.py:_console_start():2573] atexit reg
2025-05-30 10:41:13,505 INFO    MainThread:60884 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-30 10:41:13,505 INFO    MainThread:60884 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-30 10:41:13,506 INFO    MainThread:60884 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-30 10:41:13,506 INFO    MainThread:60884 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-30 10:41:13,506 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:41:13,512 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:41:13,512 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:41:13,513 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:41:13,519 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:41:13,519 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:41:13,546 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:41:27,184 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:41:27,184 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:41:27,185 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:41:27,189 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:41:27,190 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:41:28,151 INFO    MainThread:60884 [wandb_run.py:_config_callback():1436] config_cb None None {'learner': {'generic_param': {'device': 'cuda:0', 'fail_on_invalid_gpu_id': '0', 'n_jobs': '0', 'nthread': '0', 'random_state': '0', 'seed': '0', 'seed_per_iteration': '0', 'validate_parameters': '1'}, 'gradient_booster': {'gbtree_model_param': {'num_parallel_tree': '1', 'num_trees': '0'}, 'gbtree_train_param': {'process_type': 'default', 'tree_method': 'gpu_hist', 'updater': 'grow_gpu_hist', 'updater_seq': 'grow_gpu_hist'}, 'name': 'gbtree', 'specified_updater': False, 'tree_train_param': {'alpha': '0', 'cache_opt': '1', 'colsample_bylevel': '1', 'colsample_bynode': '1', 'colsample_bytree': '1', 'eta': '0.100000001', 'gamma': '0', 'grow_policy': 'depthwise', 'interaction_constraints': '', 'lambda': '1', 'learning_rate': '0.100000001', 'max_bin': '256', 'max_cat_threshold': '64', 'max_cat_to_onehot': '4', 'max_delta_step': '0', 'max_depth': '8', 'max_leaves': '0', 'min_child_weight': '1', 'min_split_loss': '0', 'monotone_constraints': '()', 'refresh_leaf': '1', 'reg_alpha': '0', 'reg_lambda': '1', 'sampling_method': 'uniform', 'sketch_ratio': '2', 'sparse_threshold': '0.20000000000000001', 'subsample': '1'}, 'updater': [{'hist_train_param': {'debug_synchronize': '0', 'extmem_single_page': '0', 'max_cached_hist_node': '18446744073709551615'}, 'name': 'grow_gpu_hist'}]}, 'learner_model_param': {'base_score': '5E-1', 'boost_from_average': '1', 'num_class': '0', 'num_feature': '768', 'num_target': '6'}, 'learner_train_param': {'booster': 'gbtree', 'disable_default_eval_metric': '0', 'multi_strategy': 'one_output_per_tree', 'objective': 'binary:logistic'}, 'metrics': [{'name': 'logloss'}], 'objective': {'name': 'binary:logistic', 'reg_loss_param': {'scale_pos_weight': '1'}}}, 'version': [3, 0, 2]}
2025-05-30 10:43:34,136 INFO    MainThread:60884 [wandb_run.py:_config_callback():1436] config_cb ('_wandb', 'visualize', 'Feature Importance') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/bar/v0', 'fieldSettings': {'label': 'Feature', 'value': 'Importance'}, 'stringSettings': {'title': 'Feature Importance'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'Feature Importance_table'}], 'fields': []}]}]}}} None
2025-05-30 10:43:34,656 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:43:34,665 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:43:34,665 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:43:35,022 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:44:04,857 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:44:04,857 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:44:05,553 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:44:10,734 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:44:10,734 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:44:10,768 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:46:34,760 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:46:34,760 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:46:34,761 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:46:41,216 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:46:41,217 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:46:41,217 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:46:54,014 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:46:54,015 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:46:54,057 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:47:16,013 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:47:16,013 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:47:16,091 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:49:11,215 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:49:11,215 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:49:11,300 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:49:37,581 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:49:37,581 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:49:37,583 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:49:53,293 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:49:53,293 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:49:53,294 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:50:29,518 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:50:29,519 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:50:29,635 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:51:38,994 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:51:38,995 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:51:38,999 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:51:42,477 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:51:42,477 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:51:43,647 INFO    MainThread:60884 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-30 10:51:48,069 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-30 10:51:48,069 INFO    MainThread:60884 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-30 10:51:48,076 INFO    MainThread:60884 [wandb_run.py:_config_callback():1436] config_cb ('_wandb', 'visualize', 'confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-05-30 10:51:48,248 INFO    MainThread:60884 [wandb_run.py:_finish():2321] finishing run michelmortier1213-hes-so-gen-ve/comments-categorizer/g1jjd4pv
2025-05-30 10:51:48,248 INFO    MainThread:60884 [jupyter.py:save_history():477] not saving jupyter history
2025-05-30 10:51:48,248 INFO    MainThread:60884 [jupyter.py:save_ipynb():401] not saving jupyter notebook
2025-05-30 10:51:48,248 INFO    MainThread:60884 [wandb_init.py:_jupyter_teardown():628] cleaning up jupyter logic
2025-05-30 10:51:48,248 INFO    MainThread:60884 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 0
2025-05-30 10:51:48,248 INFO    MainThread:60884 [wandb_run.py:_restore():2520] restore
2025-05-30 10:51:48,248 INFO    MainThread:60884 [wandb_run.py:_restore():2526] restore done
2025-05-30 10:52:36,721 WARNING MsgRouterThr:60884 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-30 10:52:36,725 INFO    MsgRouterThr:60884 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 9 handles.
2025-05-30 10:52:44,957 ERROR   MainThread:60884 [wandb_init.py:init():1687] [no run ID] error in wandb.init()
Traceback (most recent call last):
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1677, in init
    return wi.init(run_settings, run_config, run_printer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1012, in init
    backend.interface.publish_header()
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 97, in publish_header
    self._publish_header(header)
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 275, in _publish_header
    self._publish(rec)
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/marco/projects/flawfinder/comments-categorizer-model/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
